title: DAI
timezone: UTC
collections:
  clients:
    title: Clients
    output: false
  contacts:
    title: Contacts
    output: false
  experts:
    title: Experts
    output: true
    permalink: "/who-we-are/our-team/:path"
  leaders:
    title: Leaders
    output: true
    permalink: "/who-we-are/leadership/:path"
  members:
    title: Members
    output: true
    permalink: "/who-we-are/board/:path"
  news:
    title: News
    output: true
    permalink: "/news/:path"
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: true
    permalink: "/our-work/projects/:path"
  regions:
    title: Regions
    output: true
    permalink: "/our-work/regions/:path"
  related:
    title: Related
    output: false
  solutions:
    title: Solutions
    output: true
    permalink: "/our-work/solutions/:path"
  stories:
    title: Stories
    output: true
    permalink: "/publications/:path"
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: stories
  values:
    regions: 
    solutions: 
    projects: 
    clients: 
- scope:
    path: ''
    type: clients
  values:
    abbr: 
- scope:
    path: ''
    type: projects
  values:
    summary: 
    start: 
    end: 
    client: 
    solutions:
    - Include Primary and/or Secondary Solutions
    regions: 
    country: 
    promos:
    - title: 
      link: 
    layout: project
- scope:
    path: ''
    type: news
  values:
    is_featured: false
    solutions:
    - Include Primary and/or Secondary Solutions
    regions: 
    projects: 
    clients: 
    summary: 
    layout: node
    social-image: 
- scope:
    path: ''
    type: members
  values:
    summary: 
    image: 400x225
    sort-order: 
    layout: leaders
- scope:
    path: ''
    type: leaders
  values:
    job-title: 
    summary: 
    image: 400x225
    sort-order: 
    layout: leaders
- scope:
    path: ''
    type: contacts
  values:
    job-title: 
    email: 
    summary: 
    image: 136x136
    group: 
    sort-order: 
- scope:
    path: ''
    type: experts
  values:
    lastname: 
    summary: 
    job-title: 
    image: 235x235
    solutions:
    - Include Primary and/or Secondary Solutions
    regions:
    - 
    articles:
    - name: 
      article_file: 
    layout: expert
- scope:
    path: ''
    type: related
  values:
    relatedlink: include a full link to the item you want to feature
    summary: include some text that will show up alongside the title and read more
      link
date: 2016-01-01 17:11:00.000000000 Z
excerpt_separator: "<!--more-->"
markdown: kramdown
destination: "./build"
permalink: "/:title"
exclude:
- README.md
- ".gitignore"
- ".DS_Store"
- vendor
- node_modules
- build
- browser-sync.js
- gulpfile.js
sass:
  sass_dir: assets/_sass
  style: compressed
baseurl: 
url: https://www.dai.com
plugins:
- jekyll-redirect-from
- jekyll-sitemap
- github-pages
- jekyll-algolia
- shuffleit
algolia:
  nodes_to_index: 'p,h2'
  application_id: R7MRY12BR6
  index_name: dai
  files_to_exclude:
  - view-more-articles.md
  - view-more-news.md
  - our-work/projects.md
  - who-we-are/our-team.md
  - who-we-are/board.md
  - who-we-are/leadership.md
  - project-login.md
  - news/ten-years-later-steven-rosenberg-creative-father-serbia-association-local.html
  settings:
    attributeForDistinct: url
    attributesToHighlight: 
    highlightPreTag: <span class="algolia__result-highlight">
    highlightPostTag: "</span>"
    attributesToRetrieve:
    - excerpt_text
    - title
    - url
    - hierarchy
    - summary
    searchableAttributes:
    - title
    - excerpt_text
    - tags
    - hierarchy
    - summary
    attributesForFaceting:
    - layout
    - solutions
    hitsPerPage: 20
