---
title: DAI
url: http://dai.com
timezone: UTC
collections:
  contacts-business-development:
    title: Contacts Business Development
    output: false
  contacts-business-management:
    title: Contacts Business Management
    output: true
  contacts-coordinators:
    title: Contacts Coordinators
    output: false
  contacts-management:
    title: Contacts Management
    output: false
  contacts-programme-management:
    title: Contacts Programme Management
    output: false
  experts:
    title: Experts
    output: true
    permalink: "/who-we-are/our-team/:path/"
    defaults:
      parent: who-we-are
      regions:
      solutions:
  leaders:
    title: Leaders
    output: true
    permalink: "/who-we-are/leadership/:path/"
  members:
    title: Members
    output: true
    permalink: "/who-we-are/board/:path/"
  projects:
    title: Projects
    output: true
    permalink: "/our-work/projects/:path/"
  uploads:
    title: Uploads
    output: true
markdown: redcarpet
highlighter: pygments
destination: "./build"
permalink: pretty
paginate: 1
exclude:
- README.md
- ".gitignore"
- Guardfile
- Rakefile
- Gemfile
- Gemfile.lock
- ".DS_Store"
- punchlist.md
sass:
  sass_dir: assets/_sass
baseurl: ''
