---
title: DAI
url: http://dai.com
timezone: UTC
collections:
  clients:
    title: Clients
    output: false
  contacts:
    title: Contacts
    output: false
  experts:
    title: Experts
    output: true
    permalink: "/who-we-are/our-team/:path/"
  leaders:
    title: Leaders
    output: true
    permalink: "/who-we-are/leadership/:path/"
  members:
    title: Members
    output: true
    permalink: "/who-we-are/board/:path/"
  news:
    title: News
    output: true
    permalink: "/news-publications/news/:path/"
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: true
    permalink: "/our-work/projects/:path/"
  solutions:
    title: Solutions
    output: true
    permalink: "/our-work/solutions/:path/"
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: clients
  values:
    abbr: 
- scope:
    path: ''
    type: projects
  values:
    client: 
    start-date: 
    end-date: 
    regions: 
    country: 
    solutions: 
    layout: project
- scope:
    path: ''
    type: news
  values:
    date: 
    topics:
    - 
    - 
    layout: post
- scope:
    path: ''
    type: members
  values:
    image: 400x225
    summary: 
    sort-order: 
    layout: leaders
- scope:
    path: ''
    type: leaders
  values:
    image: 400x225
    job-title: 
    summary: 
    sort-order: 
    layout: leaders
- scope:
    path: ''
    type: contacts
  values:
    image: 136x136
    job-title: 
    email: 
    summary: 
    group: 
- scope:
    path: ''
    type: experts
  values:
    layout: expert
    job-title: 
    image: 235x235
    summary: 
    solutions:
    - 
    - 
    sub-solutions:
    - 
    regions:
    - 
    - 
    articles:
    - name: 
      article_file: 
gems:
- octopress-paginate
markdown: redcarpet
highlighter: pygments
destination: "./build"
permalink: pretty
paginate: 1
exclude:
- README.md
- ".gitignore"
- Guardfile
- Rakefile
- Gemfile
- Gemfile.lock
- ".DS_Store"
- punchlist.md
sass:
  sass_dir: assets/_sass
baseurl: ''
