---
title: DAI
url: http://dai.com
timezone: UTC
collections:
  contacts:
    title: Contacts
    output: false
  experts:
    title: Experts
    output: true
    permalink: "/who-we-are/our-team/:path/"
  leaders:
    title: Leaders
    output: true
    permalink: "/who-we-are/leadership/:path/"
  members:
    title: Members
    output: true
    permalink: "/who-we-are/board/:path/"
  projects:
    title: Projects
    output: true
    permalink: "/our-work/projects/:path/"
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: leaders
  values:
    image:
    job-title:
    summary:
    sort-order:
    parent: who-we-are
    layout: leaders
- scope:
    path: ''
    type: contacts
  values:
    image: 136x136
    job-title:
    email:
    summary:
    group:
    parent: who-we-are
- scope:
    path: ''
    type: experts
  values:
    layout: expert
    job-title:
    image: 235x235
    summary:
    solutions:
    -
    -
    sub-solutions:
    -
    regions:
    -
    -
    articles:
    - name:
      article_file:
    parent: who-we-are
markdown: redcarpet
highlighter: pygments
destination: "./build"
permalink: pretty
paginate: 1
exclude:
- README.md
- ".gitignore"
- Guardfile
- Rakefile
- Gemfile
- Gemfile.lock
- ".DS_Store"
- punchlist.md
sass:
  sass_dir: assets/_sass
baseurl: ''
