---
title: DAI
timezone: UTC
collections:
  clients:
    title: Clients
    output: false
  contacts:
    title: Contacts
    output: false
  experts:
    title: Experts
    output: true
    permalink: "/who-we-are/our-team/:path"
  leaders:
    title: Leaders
    output: true
    permalink: "/who-we-are/leadership/:path"
  members:
    title: Members
    output: true
    permalink: "/who-we-are/board/:path"
  news:
    title: News
    output: true
    permalink: "/news/:path"
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: true
    permalink: "/our-work/projects/:path"
  regions:
    title: Regions
    output: true
    permalink: "/our-work/regions/:path"
  related:
    title: Related
    output: false
  solutions:
    title: Solutions
    output: true
    permalink: "/our-work/solutions/:path"
  stories:
    title: Stories
    output: true
    permalink: "/publications/:path"
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: stories
  values:
    regions: 
    solutions: 
    projects: 
    clients: 
- scope:
    path: ''
    type: clients
  values:
    abbr: 
- scope:
    path: ''
    type: projects
  values:
    client: 
    start-date: 
    end-date: 
    regions: 
    country: 
    solutions: 
    layout: project
- scope:
    path: ''
    type: news
  values:
    solutions: 
    projects: 
    regions: 
    clients: 
    featured: 
    layout: node
- scope:
    path: ''
    type: members
  values:
    image: 400x225
    summary: 
    sort-order: 
    layout: leaders
- scope:
    path: ''
    type: leaders
  values:
    image: 400x225
    job-title: 
    summary: 
    sort-order: 
    layout: leaders
- scope:
    path: ''
    type: contacts
  values:
    image: 136x136
    job-title: 
    email: 
    summary: 
    group: 
- scope:
    path: ''
    type: experts
  values:
    lastname: 
    regions: 
    solutions: 
    layout: expert
    image: 235x235
    summary: 
    job-title: 
    articles:
    - name: 
      article_file: 
excerpt_separator: "<!--more-->"
markdown: kramdown
destination: "./build"
permalink: "/:title"
exclude:
- README.md
- ".gitignore"
- ".DS_Store"
- vendor
- node_modules
- build
sass:
  sass_dir: assets/_sass
  style: compressed
baseurl: 
gems:
- jekyll-redirect-from
