---
title: DAI
timezone: UTC
collections:
  clients:
    title: Clients
    output: false
  contacts:
    title: Contacts
    output: false
  experts:
    title: Experts
    output: true
    permalink: "/who-we-are/our-team/:path"
  leaders:
    title: Leaders
    output: true
    permalink: "/who-we-are/leadership/:path"
  members:
    title: Members
    output: true
    permalink: "/who-we-are/board/:path"
  news:
    title: News
    output: true
    permalink: "/news/:path"
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: true
    permalink: "/our-work/projects/:path"
  regions:
    title: Regions
    output: true
    permalink: "/our-work/regions/:path"
  related:
    title: Related
    output: false
  solutions:
    title: Solutions
    output: true
    permalink: "/our-work/solutions/:path"
  stories:
    title: Stories
    output: true
    permalink: "/publications/:path"
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: stories
  values:
    regions:
    solutions:
    projects:
    clients:
- scope:
    path: ''
    type: clients
  values:
    abbr:
- scope:
    path: ''
    type: projects
  values:
    start:
    end:
    client:
    solutions:
    - Include Primary and/or Secondary Solutions
    regions:
    country:
    promos:
    - title:
      link: 
    layout: project
- scope:
    path: ''
    type: news
  values:
    is_featured: false
    solutions:
    - Include Primary and/or Secondary Solutions
    regions:
    projects:
    clients:
    layout: node
- scope:
    path: ''
    type: members
  values:
    summary:
    image: 400x225
    sort-order:
    layout: leaders
- scope:
    path: ''
    type: leaders
  values:
    job-title:
    summary:
    image: 400x225
    sort-order:
    layout: leaders
- scope:
    path: ''
    type: contacts
  values:
    job-title:
    email:
    summary:
    image: 136x136
    group:
- scope:
    path: ''
    type: experts
  values:
    lastname:
    summary:
    job-title:
    image: 235x235
    solutions:
    - Include Primary and/or Secondary Solutions
    regions:
    articles:
    - name:
      article_file:
    layout: expert
- scope:
    path: ''
    type: related
  values:
    relatedlink: include a full link to the item you want to feature
    summary: include some text that will show up alongside the title and read more
      link
excerpt_separator: "<!--more-->"
markdown: kramdown
destination: "./build"
permalink: "/:title"
exclude:
- README.md
- ".gitignore"
- ".DS_Store"
- vendor
- node_modules
- build
sass:
  sass_dir: assets/_sass
  style: compressed
baseurl:
