# Setup - variables available at site.data.meta.title, site.data.meta.tagline, etc.
title: DAI
description: DAI works on the frontlines of international development. Transforming ideas into action—action into impact. We are committed to shaping a more livable world.
version:          0.1
